a = input('Digite algo: ')
print('O tipo primitivo desse valor é: ', type(a))
print('Só tem espaços? ', a.isspace())
print('É alfabético? ', a.isalpha())
print('Só tem números? ', a.isnumeric())
print('Tem números e letras? ', a.isalnum())
print('Esta em Maiúsculas? ', a.isupper())
print('Esta em Minúsculas? ', a.islower())
print('É um número decimal? ', a.isdecimal())
print('Está capitalizada? ', a.istitle())
